[package]
name = "postgres-es"
version = "0.2.0"
authors = ["Dave Garred <dave.garred@serverlesstechnology.com>"]
edition = "2018"
license-file = "LICENSE"
keywords = ["cqrs", "event-sourcing", "serverless", "lambda"]
description = "A Postgres implementation of an event store for cqrs-es."
repository = "https://github.com/serverlesstechnology/postgres-es"
documentation = "https://docs.rs/postgres-es"
readme = "README.md"

[dependencies]
#cqrs-es = "0.2.0"
cqrs-es = {version = "0.2.0", path = "../cqrs"}

async-trait = "0.1.51"
r2d2_postgres = "0.18.1"
serde = { version = "1.0.126", features = ["derive"]}
serde_json = "1.0.64"
tokio = { version = "1", features = ["macros", "rt"] }

[dev-dependencies]
static_assertions = "0.3"
uuid = { version = "0.8.2", features = ["v4"]}