[package]
name = "postgres-es"
version = "0.1.0"
authors = ["Dave Garred <dgarred@starbucks.com>"]
edition = "2018"


[dependencies]
#cqrs-es = "0.0.10"
cqrs-es = { git = "https://github.com/serverlesstechnology/cqrs.git", branch = "master"}

postgres = {version = "0.15.2", features = ["with-serde_json"]}
serde = { version = "1.0.104", features = ["derive"]}
serde_json = "1.0"
chrono = "0.4.11"

[dev-dependencies]
static_assertions = "0.3"
uuid = { version = "0.8", features = ["v4"]}