[package]
name = "postgres-es"
version = "0.0.1"
authors = ["Dave Garred <dave.garred@serverlesstechnology.com>"]
edition = "2018"
license-file = "LICENSE"
keywords = ["cqrs", "event-sourcing", "serverless", "lambda"]
description = "A Postgres implementation of an event store for cqrs-es."
repository = "https://github.com/serverlesstechnology/postgres-es"
readme = "README.md"

[dependencies]
cqrs-es = "0.0.10"

postgres = {version = "0.15.2", features = ["with-serde_json"]}
serde = { version = "1.0.104", features = ["derive"]}
serde_json = "1.0"
chrono = "0.4.11"

[dev-dependencies]
static_assertions = "0.3"
uuid = { version = "0.8", features = ["v4"]}