version: '3.1'

services:
#  ps-tests:
#    build:
#      context: .
#    links:
#      - db
#    depends_on:
#      - db
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_pass
    volumes:
      - './db:/docker-entrypoint-initdb.d'